<footer class="footer">
    <p>Tento software je licencován dle podmínek licence <a href="http://opensource.org/licenses/MIT">MIT Open Source Initiative</a>.</p>
    <p>Aplikace používá ve svém zdrojovém kódu následující softwarové balíčky a služby:</p>
    </p>
    <ul class="footer-links">
      <li><a href="http://jquery.com">jQuery</a></li>
      <li class="muted">&middot;</li>
      <li><a href="http://getbootstrap.com">Bootstrap</a></li>
      <li class="muted">&middot;</li>
      <li><a href="http://momentjs.com/">moments</a></li>
      <li class="muted">&middot;</li>
      <li><a href="https://eonasdan.github.io/bootstrap-datetimepicker/">Datepicker</a></li>
      <li class="muted">&middot;</li>
      <li><a href="http://openlayers.org/">Open Layers 3</a></li>
      <li class="muted">&middot;</li>
      <li><a href="https://www.openstreetmap.org/">OpenStreetMap</a></li>
      <li class="muted">&middot;</li>
      <li><a href="https://www.bing.com/maps/">Bing Maps</a></li>
      <li class="muted">&middot;</li>
      <!--
      <li><a href="http://www.mapquest.com/">MapQuest</a></li>
      <li class="muted">&middot;</li>
      <li><a href="https://www.python.org/download/releases/3.0/">python 3</a></li>
      <li class="muted">&middot;</li>
      -->
      <li><a href="http://www.cherrypy.org/">CherryPy</a></li>
      <li class="muted">&middot;</li>
      <li><a href="http://www.makotemplates.org/">mako</a></li>
      <li class="muted">&middot;</li>
      <li><a href="http://pytz.sourceforge.net/">pytz</a></li>
      <li class="muted">&middot;</li>
      <li><a href="http://api.mongodb.org/python/current/">PyMongo</a></li>
      <li class="muted">&middot;</li>
      <li><a href="https://www.mongodb.org/">MongoDB</a></li>
      <li class="muted">&middot;</li>
      <li><a href="https://github.com/google/code-prettify">Code Prettify</a></li>
      <li class="muted">&middot;</li>
      <li><a href="http://www.virtuosoft.eu/code/bootstrap-touchspin/">TouchSpin</a></li>
    </ul>
    <p>
    &copy; Aplikaci navrhl a vyvinul  <!-- <a href="https://github.com/N4M3Z">Martin Zeman</a> v rámci projektu CITS pro --> <a href="http://http://www.cortec.cz/">CORTEC s.r.o.</a> v roce 2015
    &middot; verze 1.1
    </p>
</footer>
